server:
  port: 8080

# swagger 是否开启
swagger:
  enable: true

#  spring 配置
spring:
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql:///zang-yue?serverTimezone=UTC
      username: root
      password: lhfadmin
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: 8d2ee93b908734f185e7
#            client-secret: df4e6b14071456dd80231ef2d34bf6db98d548e6
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/github"
#        provider:
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
logging:
  level:
    com.zy: debug


